name: lambox
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  speech_to_text: ^2.3.0
  flutter_tts: ^1.2.6
  audioplayers: ^0.15.1
  time: ^1.3.0

  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5

  provider: ^4.3.2+2
  geolocator: ^6.1.0

  font_awesome_flutter: ^8.8.1
  avatar_glow: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
